name: DIY

on:
  workflow_dispatch:
  schedule:
    - cron: "0 1 * * *"
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Sync from Upstream
      uses: repo-sync/github-sync@v2
      with:
        source_repo: ccfddl/ccf-deadlines
        mount_workspace: true
        source_branch: main
        destination_branch: main
        merge_method: rebase
        github_token: ${{ secrets.GITHUB_TOKEN }}
    - name: Setup Node.js environment
      uses: actions/setup-node@main
      with:
        node-version: '15.x'
    - name: Set up Python 3.9
      uses: actions/setup-python@v1
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install PyYAML jsonschema icalendar xlin
    - name: Validate yml files
      run: |
        python ./scripts/validate
    - name: Assemble yml files
      run: |
        mkdir -p public/conference && cd public/conference
        awk 1 `find ../../conference -name '*.yml' -not -path '**/types.yml'` > allconf.yml
        awk 1 `find ../../accept_rates -name '*.yml'` > allacc.yml
        cp ../../conference/types.yml .
        cd ../..
    - name: Generate iCal files
      run: |
        python cli/ccfddl/convert_to_ical_diy.py --conf ${{ vars.CONFERENCES_NAME}}
        # generate deadlines_diy_en.ics
    - name: Configure Git
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
    
    - name: Fetch all branches
      run: git fetch origin

    - name: Checkout or create release branch
      run: |
        # Backup the generated iCal file
        cp deadlines_diy_en.ics /tmp/deadlines_diy_en.ics
        
        # Check if release branch exists remotely
        if git ls-remote --heads origin release | grep -q release; then
          # Branch exists, just checkout
          git checkout release
        else
          # Create new empty orphan branch
          git checkout --orphan release
          git rm -rf .
        fi
        
        # Restore the iCal file
        cp /tmp/deadlines_diy_en.ics deadlines_diy_en.ics
    - name: Update iCal file
      run: |
        # Add the generated iCal file
        git add *.ics
    - name: Commit and Push
      run: |
        git diff-index --quiet HEAD || git commit -m "Update deadlines_diy_en.ics"
        git push origin release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}